### ISSUE TITLE
Redis - Revise and correct methods that potentially can return `null` values

### ISSUE THREAD

**Issue by paualarco** [monix/monix-connect#156]
monix-redis is built on top of lettuce, and some of their methods can return a null values instead of the expected one, which makes it unsafe and not reliable.

An example of this is the hget from the Hash api ([this one is already corrected](https://github.com/monix/monix-connect/pull/143/files), but there are more, and the idea was to identify these methods that can potentially return null and wrap them with Option.

Currently the methods have unit-tested under test, on the other handit contains functional tests that runs agains a redis docker container. But these just cover a few examples.

A way of ensuring that no null values are returned would be to add functional tests that handles different scenarios.
So in case of hget , it would return null when called for a key and field that does not exist.

A good way to find the methods that returns values is by directly checking the underlying api documentation.

**Comment by ttymck** [comment]
I'd like to handle this issue. It looks like the desired solution is to just use `Task.fromReactivePublisher` directly, bypassing the `fromMono` logic? I tried this on `RedisSortedSet#bzpopmax` and it seems to work ([here](https://github.com/ttymck/monix-connect/pull/1/files#diff-43dff7b5fe481ef43975f2391ddb48be1066d31d1fe15d2aa93c96021bdd2b69R29-R37)). If so I will track down the rest of the `nil` returning APIs and submit a PR!

**Comment by paualarco** [comment]
Hello @ttymck,

Thanks for your interest in the project :)

That's a good example 👍   Although `MonoOps` is not necessary I believe.

I know this change it is not needed in all the methods but for some of them is, and the thing is that just by looking at the documentation we don't know whether the signature might return an empty `Mono` or not.

Maybe a good approach approach would be to write integration tests for the different redis modules and each of the operations, currently, there is only one integration test suite `RedisIntegrationTest` that just covers a few of them.

**Comment by paualarco** [comment]
@ttymck what do you think?

**Comment by ttymck** [comment]
> Maybe a good approach for the moment would be to write integration tests for the different redis modules and each of the operations, currently, there is only one integration test suite RedisIntegrationTest that just covers a few of them.

@paualarco i can definitely do that. Would you want separate (flat) test suites i.e. `RedisSortedSetIntegrationTest`, etc or one structured free/word spec?

**Comment by paualarco** [comment]
@ttymck as you can see, all the modules in the project use the `Spec` suffix for normal tests `Suite` for the integration ones. Could you follow that convention? The Redis ones are an exception at the moment, we should sync it with the rest :P

**Comment by ttymck** [comment]
@paualarco i started with an integration suite for `RedisSortedSet` operations that can return `nil`: [RedisSortedSetSuite.scala ](https://github.com/ttymck/monix-connect/pull/1/files#diff-86f9a9d650a3a6bf3a805d077088c9b9d7737a9681d80c143fbbe735fbd0ae0d)

please let me know if I'm heading in the right direction, and I can add suites for the other modules.

**Comment by paualarco** [comment]
Left a comment, and a question, still not sure if we should return None in those cases, maybe better to stick with a failed task.

**Comment by ttymck** [comment]
@paualarco I feel I've misunderstood the objective of this issue. I will see if there is a better first task for me to get familiar with this project.

**Comment by paualarco** [comment]
@ttymck sorry for confusing you, I was a bit too :/

have reverted the example integration test for hget, since I think we should only return a failed task rather than an empty option. https://github.com/monix/monix-connect/issues/480

closing this issue now, have created new ones for writing integration test for each of the redis submodules,
feel free to ask more info if the the requirement is not clear :)

**Comment by ttymck** [comment]
@paualarco understood, I'll take a look at the integration tests 😄
