### ISSUE TITLE
GCS Connector is missing in maven

### ISSUE THREAD

**Issue by YulawOne** [monix/monix-connect#250]
Looks like monix-gcs was never released as there no artifact in maven - https://search.maven.org/search?q=a:monix-gcs*

**Comment by paualarco** [comment]
@YulawOne thanks for reporting that, I noticed yesterday when doing the release... 🤦

**Comment by paualarco** [comment]
@YulawOne released **monix-gcs** `0.3.1`

**Comment by paualarco** [comment]
@YulawOne released **monix-gcs** on _0.3.3_ 
https://oss.sonatype.org/#nexus-search;quick~monix-gcs

**Comment by paualarco** [comment]
Please, let us know if you have issues any other issues 👍
