### ISSUE TITLE
Web documentation

### ISSUE THREAD

**Issue by paualarco** [monix/monix-connect#27]
Migrate current documentation from project's readme to a web version in `monix.io/connect/`.

**Comment by Avasil** [comment]
> Cool, I realised that monix-bio follows a different web documentation style, and as per the comments I saw in Monix vNext, there might be a plan to do some changes on that aspect... we should probably need to start a discussion about that

Yeah, I wanted to try something else and I plan to continue with github sites there. I feel like the current website and docs need an overhaul but it was easier for me to setup it this way than change `monix.io`. At some point it would be nice to have everything under `monix.io` though.

**Comment by paualarco** [comment]
Totally agree, at some point will be nice to have all in the same style. This project has not reached the point to start having online documentation online yet, but we'll see.

**Comment by paualarco** [comment]
@Avasil I was looking for existing web documentation built with microsites and found one that looks very nice to me: https://cir.is/  
The main reason I like it is because the margins are very well delimited at left and right ( I realised that most of microsites does not have right margin in which IMO it makes it difficult to read.

**Comment by Avasil** [comment]
I agree it looks great - I also like the table of contents on the right, e.g. https://cir.is/docs/overview#getting-started

We could try replicating similar setup in `monix-bio` which already has microsite but I have followed Cats-Effect setup which doesn't look nearly as nice.

**Comment by Avasil** [comment]
I have created a PR with docusaurus: https://github.com/monix/monix-bio/pull/128

I will try to merge it as soon as possible and publish the site

I based the configuration on ciris but by default the landing page looks similar to this: https://scalacenter.github.io/scalafix/

**Comment by paualarco** [comment]
@Avasil is this issue a blocker for publishing scaladoc? I guess this project would need its domain or access to an already existing one.

**Comment by Avasil** [comment]
I would suggest to setup gh-sites in the same way as `monix-bio` - it has published scaladoc as well.

I have followed these instructions:
- https://docusaurus.io/docs/en/installation
- https://scalameta.org/mdoc/docs/docusaurus.html

And then ciris setup 
It should be quite easy to copy from `monix-bio`

AFAIK scaladoc in `monix.io` is done in a primitive manner - it is a copy paste of unidoc result x) https://github.com/monix/monix.io/tree/master/api/3.2

I would like to have everything under `monix.io` one day but I went with the easiest way which didn't require me to meddle with `monix.io` since I'm not very familiar with it :D

**Comment by paualarco** [comment]
Thank you @Avasil, will follow these instructions :)

**Comment by paualarco** [comment]
(dummy question spoiler) 
@Avasil did you managed to see the website locally? 
When I run `sbt docs/docusaurusCreateSite` the index.html is created under `website/build`, but don't know how to open it with its correspondent css and js?

**Comment by Avasil** [comment]
After `docusaurusCreateSite` you need to go to `website` directory and call `yarn start`

**Comment by paualarco** [comment]
Had to make a small [change](https://github.com/scalameta/mdoc/pull/345) on mdoc to get it working with github actions. 
Now it is correctly publishing the web documentation :) 
see https://monix.github.io/monix-connect/

**Comment by Avasil** [comment]
Looks awesome, good job!
I looks like there are no API Docs yet
