### ISSUE TITLE
Redis - Remove lettuce types dependencies

### ISSUE THREAD

**Issue by paualarco** [monix/monix-connect#36]
Currently, monix redis connector exposes lettuce specific types that are needed for performing redis commands.
Would be great to study if we can define our own types and conversions from and forth. 
 
So as a result, the user would not have to deal with these, neither for passing them as parameter to functions nor when getting it as result. 

The aim is to reduce the user having to import the less monix external types as possible and to make the api more scala like. (No builders, use companion objects etc.)

Some examples of these might be found along the different Apis:

`import io.lettuce.core.{KeyValue, Limit, Range, ScoredValue, ScoredValueScanCursor, KeyScanCursor, StreamMessage}`

**Comment by t1707** [comment]
Hi, It will be a great help if you could some description, Thanks in advance 😄

**Comment by paualarco** [comment]
@t1707 I have updated the description, thanks for remembering to do this :)

**Comment by Avasil** [comment]
BTW do you have any mid/long term plans to get rid of lettuce dependency and write a native connector, similarly to laserdisc or zio-redis? Maybe we could even collaborate if it's possible to support both fs2 and Observable without conversions

**Comment by paualarco** [comment]
@Avasil yeah thought about that already, and it is actually a good idea! I went with `lettuce` since I was familiarised with it already which means it was much faster to implement for me.  
Not a priority for me ATM, but might be worth investing more time on it than keep iterating over the current one.
Created an [issue](https://github.com/monix/monix-connect/issues/148) in case anyone gets interested on it.

**Comment by t1707** [comment]
Apologies for commenting out of the box, even though I also support the idea of removing any third-party dependency but using 3P libraries also give us the extra time to work on other features.

So in the end, It all depends on the long term plan of the library(as stated by Piotr).

The idea I have for `Elasticsearch` also relies on using `Elastic4s` library but again that might create an extra liability for us and it's better to write a native es-connect same as the `Alpakka` people.
https://doc.akka.io/docs/alpakka/current/elasticsearch.html

What do you guys thing?

**Comment by Avasil** [comment]
It's better to have a simple wrapper than nothing. :D 
Consider your time and how much effort are you willing to put into it and decide based on that

I think it's nicer to have "native" connectors but it's extra work and not always worth it. It's probably better to cover a wide range of connectors quickly and then work on improving the most important ones.

**Comment by paualarco** [comment]
Totally agree with that. 

So I would say, take a look first at the different ways to solve the problem, and then do the balance between complexity / short and long term, etc.

**Comment by t1707** [comment]
Agree, better to first work on wrappers and then on native connectors.
