### ISSUE TITLE
Redis Benchmarks

### ISSUE THREAD

**Issue by paualarco** [monix/monix-connect#368]
Create redis benmchmarks and compare it with other existing scala redis integrations. 
See redis4cats, laserdisc, zio-redis...

**Comment by GKhotyan** [comment]
I'll try this issue

**Comment by paualarco** [comment]
@GKhotyan there is a lot of methods to be tested within _redis_, I don't think we need to benchmark each of them since it will be difficult to maintain. It would be good to compare it with other libraries to actually see if the fact of using the underlying `lettuce` a constrain on terms of performance.

So I would start with a couple of methods of each module. Excluding `PubSub`, `Server` and `Stream`, since they are incomplete.
