### ISSUE TITLE
Redis - Revise and correct methods that potentially can return `null` values

### ISSUE THREAD

**Issue by paualarco** [monix/monix-connect#37]

**Comment by TapanVaishnav** [comment]
Hi @paualarco 
I'd like to challenge on this one. 
It would be helpful if you could give some insights regarding where to start from?

**Comment by paualarco** [comment]
Hi @TapanVaishnav 

That would be great! Thanks for your interest :D 

I should have written a description... Let me explain the problem and the solution that I had mind:

So `monix-redis` is built on top of _lettuce_, and some of their methods can return a `null` values instead of the expected one, which makes it unsafe and not reliable.

An example of this is the `hget` from the `Hash` api, but there are more, and the idea was to identify these methods that can potentially return `null` and wrap them with `Option`. 

Currently the methods have unit-tested under `test`, on the other hand`it` contains functional tests that runs agains a redis docker container. But these just cover a few examples. 

A way of ensuring that no null values are returned would be to add functional tests that handles different scenarios. 
So in case of `hget` , it would return null when called for a _key_ and _field_ that does not exist.

A good way to find the methods that returns values is by directly checking the [underlying api documentation](https://github.com/git-stu/lettuce/blob/master/src/main/java/com/lambdaworks/redis/api/async/RedisHashAsyncCommands.java#L52).

In case you still interested on working on that, we could create different issues for each of the `Redis` APIS since the overall number of methods can be high.

For any related question please, ask! :D

**Comment by TapanVaishnav** [comment]
Hi @paualarco, 
Thank you for your quick response and detailed explanation.
> In case you still interested on working on that, we could create different issues for each of the Redis APIS since the overall number of methods can be high. 
Yeah, I agree, it's better to make a separate issue for each method and I will start working on that.

I haven't actually tested it yet but are you thinking something like this?
```
def hget[K, V](key: K, field: K)(implicit connection: StatefulRedisConnection[K, V]): Task[V] =
    Task.from(connection.reactive().hget(key, field) match {
      case v if v != null => v
      case _ => Mono.empty()
    })
```

**Comment by paualarco** [comment]
I suspect that would not work since `Mono.empty()` would return `Mono[Nothing]`?
What I had in mind was just to wrap the returned value within an `Option`, which would return `None` for `null`, otherwise `Some(V)`.

```
def hget[K, V](key: K, field: K)(implicit connection: StatefulRedisConnection[K, V]): Task[Option[V]] =
    Task.from(Option(connection.reactive().hget(key, field)))
```

**Comment by TapanVaishnav** [comment]
```
def hget[K, V](key: K, field: K)(implicit connection: StatefulRedisConnection[K, V]): Task[Option[V]] =
    Task.from(Option(connection.reactive().hget(key, field)))
```
I tried this and this is giving the compatibility error as required is `Option` but found `Mono`, also even if we wrap it with `Option`, I doubt if that would prevent the hget from raising an error.

Also do you have any other mode of communication than git? (It's rather slow discussing here) 😅

**Comment by TapanVaishnav** [comment]
I think something like this might work
```
def hget[K, V](key: K, field: K)(implicit connection: StatefulRedisConnection[K, V]): Task[Option[V]] =
    Task.fromReactivePublisher(connection.reactive().hget(key, field) match {
      case v => v
      case _ => Mono.empty()
    })
```

Test
```
  s"${RedisHash}" should "access non existing key in redis and should return None" in {
    //given
    val key: K = genRedisKey.sample.get
    val field: K = genRedisKey.sample.get
    val value: String = genRedisValue.sample.get.toString

    //when
    //RedisHash.hset(key, field, value).runSyncUnsafe()

    //and
    val t = RedisHash.hget(key, field).runSyncUnsafe()

    //then
    val r = t
    r shouldBe None
  }
```

**Comment by paualarco** [comment]
> ```
> def hget[K, V](key: K, field: K)(implicit connection: StatefulRedisConnection[K, V]): Task[Option[V]] =
>     Task.from(Option(connection.reactive().hget(key, field)))
> ```
> 
> I tried this and this is giving the compatibility error as required is `Option` but found `Mono`, also even if we wrap it with `Option`, I doubt if that would prevent the hget from raising an error.

Sorry that was completely wrong typed, I meant this:

> ```
> def hget[K, V](key: K, field: K)(implicit connection: StatefulRedisConnection[K, V]): Task[Option[V]] =
>     Task.from(connection.reactive().hget(key, field)).map(_ => Option(_)))
> ```

IMO looks shorter and more readable than:

```
match {
      case v => v
      case _ => Mono.empty()
    })
```

> Also do you have any other mode of communication than git? (It's rather slow discussing here) 😅

Feel free to reach me privately on gitter ;)
Also Monix Connect project has its [own channel](https://gitter.im/monix/monix-connect?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).

**Comment by t1707** [comment]
Hi, would like to close this as the corresponding PR is also merged. 🚀

**Comment by paualarco** [comment]
@t1707 we can close this one, and create other issues for reviing other redis apis.
