### ISSUE TITLE
Write integration tests for the RedisHash module 

### ISSUE THREAD

**Issue by paualarco** [monix/monix-connect#474]

**Comment by ttymck** [comment]
I'd be glad to write the suite for this. I have started a pr [here](https://github.com/ttymck/monix-connect/pull/2), if you have time to take a look and see if I am on the right track, that would be appreciated! I left a few questions regarding design/code reuse.

**Comment by paualarco** [comment]
Done as part of https://github.com/monix/monix-connect/pull/590
