### ISSUE TITLE
awsAuth not published

### ISSUE THREAD

**Issue by ThijsBroersen** [monix/monix-connect#481]
Just discovered this awesome repo and tried to pull monix-s3 0.5.0 but it seems it depends on awsAuth which doesn't look like to be published... I noticed skipOnPublishSettings is set for this module.

**Comment by paualarco** [comment]
My bad, thanks for raising that! Will be fixed asap

**Comment by paualarco** [comment]
It is correctly published on `0.5.1`, please let us know if you find any other issue :)
