### ISSUE TITLE
Deprecate akka-connector

### ISSUE THREAD

**Issue by paualarco** [monix/monix-connect#50]
Maybe rename akka connector for reactive streams or just create new ones for ZIO and FS2.

**Comment by paualarco** [comment]
Closed by https://github.com/monix/monix-connect/pull/52

**Comment by t1707** [comment]
+1 for `just create new ones for ZIO and FS2.`

**Comment by paualarco** [comment]
Yeah that sounds good

**Comment by paualarco** [comment]
@Avasil guess `ZIO` conversion are better covered on [monix-bio](https://monix.github.io/monix-bio/docs/cats-effect#ziozio)

**Comment by Avasil** [comment]
What do you have in mind as this connector/module?

A while ago I wrote https://monix.io/docs/3x/reactive/observable.html#interoperability-with-other-streams-api-akka-streams-fs2 (ZIO Streams didn't exist at the time)

I feel like a doc could be good enough unless you want to wrap API

**Comment by paualarco** [comment]
@Avasil I guess yeah its a wrapper but still can reduce some boilerplate code and make it more idiomatic, since monix provide generic reactive streams interoperability but not specific to the library.

For example the Monix documentation only shows how to convert an akka `Source` to `Observable`, but the `monix-akka` conector makes it easier for the user to perform such conversion and also [provides conversions](https://github.com/monix/monix-connect/blob/master/akka/src/main/scala/monix/connect/akka/stream/Converters.scala#L64) from `Sink` to `Consumer` and viceversa just by typing `.asSink`,  `asSource` or `asConsumer`, `asObservable`.  

I was just contemplating to do something similar for `Fs2` and `Zio` to provide something like `observable.asZStream` and `consumer.asZSink`.

**Comment by paualarco** [comment]
I think better thing would be to add docs on how to convert to different Reactive streams implementations (Akka, FS2, ZIO, Reactor...), as @Avasil suggested, which will help dependency management on the user side. 
So, will be deprecating the `akka-connector` in the next releases if no one opposes :)

**Comment by Avasil** [comment]
Yup, I still think docs are good enough 👍 
They just need an update/be more visible

I'm planning an overhaul but with my pace it's going to be 2025 🙈
