### ISSUE TITLE
reference config cannot be merged for fat jar

### ISSUE THREAD

**Issue by borissmidt** [monix/monix-connect#780]
It seem that because you are using a leading { and trailing } for your config it becomes an invalid reference.conf when merging the reference files. in a fat jar

**Comment by paualarco** [comment]
Interesting! Do you have by chance a reproducible example? :D

**Comment by borissmidt** [comment]
Not really but i removed the brackets in a project and published it locally
and that solved the problem.

The following is an example of an invalid config:

```
Hello = 10

{
 Config = 20
}
```

**Comment by paualarco** [comment]
@borissmidt feel free to open a PR to fixing it :) 
if you don't have time or interest I will do

**Comment by borissmidt** [comment]
There is one open already :) it just need to be accepted

**Comment by paualarco** [comment]
Oh, I missed it, thanks for highlighting it :)
