### ISSUE TITLE
Incorrect part numbers in multipart uploads

### ISSUE THREAD

**Issue by rfkm** [monix/monix-connect#814]
Hello. I have noticed that multipart uploads do not work properly in my environment. The reason seems to be that the part number is not correct. Part number must be between 1 and 10,000, so 0 cannot be used (ref. https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html ).
I'm using a S3 compatible service, so I don't know how it behaves in AWS, but at least it seems to violate the specification.

**Comment by paualarco** [comment]
Thanks for reporting this bug! Surprisingly it did not resulted in an issue on integration tests, although they also use a S3 compatible service. It's fixed it in #818

**Comment by rfkm** [comment]
Thanks for the quick fix!
