### ISSUE TITLE
`MultipartDownloadObservable` unnecessarily calls `ListObjects`

### ISSUE THREAD

**Issue by rfkm** [monix/monix-connect#963]
We have recently encountered an issue where multi part downloads are causing a lot of lock contention due to calls to `ListObjects`, resulting in poor performance. 
https://github.com/monix/monix-connect/blob/cb3f2c243c2fcc02799a2470576497ae2ddef2d8/s3/src/main/scala/monix/connect/s3/MultipartDownloadObservable.scala#L48-L56

This may be a problem that depends on the specific object storage implementation (we use Ceph), but in general I don't think it is necessary to use `ListObjects` to know size of an object. I think `HeadObject` is more appropriate.

**Comment by paualarco** [comment]
Thank you for reporting it 👍🏻
I will have a look soon. Unless you want to contribute?

**Comment by rfkm** [comment]
We are currently trying to apply an ad-hoc patch internally to verify that it really solves our problem. I can send you the patch later, but it may take some time, so I just wanted to report it first. You may go ahead and fix it, thanks!

**Comment by paualarco** [comment]
@rfkm I've released the fix on `0.6.4`, please let me know if the performance has improved 👍🏻

**Comment by rfkm** [comment]
Thank you! We have seen a significant improvement in performance in our environment.
